baseURL = "https://mdrupp.com"
title = "mdrupp.com"
languageCode = "en-us"
theme = "marius-terminal"

[pagination]
  pagerSize = 10

[params]
dateFormat = "2 Jan '06"
homeTitle = "Journal"
homeSections = ["journal"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menus]
  [[menu.main]]
  name = "Journal"
  url = "/journal/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5
  [[menu.main]]
  name = "Notes"
  url = "http://notes.mdrupp.com"
  weight = 7
  [menu.main.params]
    target = "_blank"
    rel = "noopener noreferrer"

