baseURL = "http://localhost:1313/"
title = "mdrupp.com"
languageCode = "en-us"
theme = "marius-terminal"

[pagination]
  pagerSize = 10

[params]
dateFormat = "2 Jan '06"
homeTitle = "Journal"
homeSections = ["journal"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menus]
  [[menus.main]]
  name = "Journal"
  url = "/journal/"
  weight = 1

  [[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

  [[menus.main]]
  name = "About"
  url = "/about/"
  weight = 5

